# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0263ef4c1755e579208bbafc95852a1882ca332349e066f5f6466d1edf7b9c05d205cedad27f799bede3246f590c81c276cac522068d6880cf5576bda9befaa8

test:
  secret_key_base: 1dc8c99ebb521b42180a3a1078d8c295a203ddadb28b3f9b1b4503f4ce310adc133559c19cdb3724139e40b71763dc3f20600686a08c4c80aca2fa291af3a709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
